name: Develop Branch Pipeline

on:
  push:
    branches:
      - develop

jobs:
  pull-code:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create custom folder and copy content
        run: |
          mkdir my-folder
          copy test.txt my-folder\
          echo "Code copied to my-folder"
